### ISSUE TITLE
[Feature request] Adding multiple authors for a post

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/klogw.github.io#8]
This doesn't seem to be possible using the current template.

**Comment by jchodera** [comment]
It should be easy to fix the current template to include multiple authors.

**Comment by bas-rustenburg** [comment]
Could be helpful. http://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll

**Comment by bas-rustenburg** [comment]
See #9 for updates.
